<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/14 21:56:57
sfConfig::add(array(
  'app_url_practil' => 'http://localhost/practil/web/frontend_dev.php/',
  'app_url_scorecard' => 'http://localhost/scorecard/web/frontend_dev.php/',
  'app_module_user_xml' => 'xml_servicio_usuario/',
  'app_module_user_json' => 'json_servicio_usuario/',
  'app_session_current_user' => 's_current_user',
));
