<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 21:49:03
sfConfig::add(array(
  'app_url_practil' => 'http://localhost/practil/web/frontend_dev.php/',
  'app_url_scorecard' => 'http://localhost/score_card_practil/trunk/scored_card_practil/web/frontend_dev.php/',
  'app_module_user_xml' => 'xml_servicio_usuario/',
  'app_module_user_json' => 'json_servicio_usuario/',
  'app_session_current_user' => 's_current_user',
  'app_session_current_user_name' => 's_current_user_name',
  'app_session_tree_production' => 's_tree_prodcution',
));
