<?php
// auto-generated by sfViewConfigHandler
// date: 2011/11/24 17:46:23
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('ECOTree.css', '', array ());
  $response->addStylesheet('inicio.css', '', array ());
  $response->addStylesheet('login.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('ui/jquery.ui.all.css', '', array ());
  $response->addJavascript('ECOTree.js', '', array ());
  $response->addJavascript('jquery.min.js', '', array ());
  $response->addJavascript('jquery-ui.js', '', array ());
  $response->addJavascript('sc.js', '', array ());
  $response->addJavascript('sc-ajax.js', '', array ());
  $response->addJavascript('sc-tree.js', '', array ());


