<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 21:49:04
sfConfig::add(array(
  'mod_componente_login_enabled' => true,
  'mod_componente_login_view_class' => 'sfPHP',
));
