<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 21:49:28
sfConfig::add(array(
  'mod_componente_home_enabled' => true,
  'mod_componente_home_view_class' => 'sfPHP',
));
