<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 21:49:46
sfConfig::add(array(
  'mod_production_strategy_enabled' => true,
  'mod_production_strategy_view_class' => 'sfPHP',
));
