<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_sc' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/26/11 17:34:48
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserScPeer extends BaseUserScPeer {

} // UserScPeer
