<?php


/**
 * This class defines the structure of the 'asignacion_sc' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:13
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AsignacionScTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AsignacionScTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('asignacion_sc');
		$this->setPhpName('AsignacionSc');
		$this->setClassname('AsignacionSc');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('GRUPO_ID', 'GrupoId', 'INTEGER', 'grupo_trabajo_sc', 'ID', false, null, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', true, 50, null);
		$this->addForeignKey('TREE_ID', 'TreeId', 'INTEGER', 'tree_sc', 'ID', true, null, null);
		$this->addForeignKey('INDICADOR_ID', 'IndicadorId', 'INTEGER', 'indicators_sc', 'ID', true, null, null);
		$this->addColumn('FLAG', 'Flag', 'LONGVARCHAR', false, null, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user_sc', 'ID', false, null, null);
		$this->addColumn('CREATE_AT', 'CreateAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATE_AT', 'UpdateAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('GrupoTrabajoSc', 'GrupoTrabajoSc', RelationMap::MANY_TO_ONE, array('grupo_id' => 'id', ), null, null);
    $this->addRelation('TreeSc', 'TreeSc', RelationMap::MANY_TO_ONE, array('tree_id' => 'id', ), null, null);
    $this->addRelation('IndicatorsSc', 'IndicatorsSc', RelationMap::MANY_TO_ONE, array('indicador_id' => 'id', ), null, null);
    $this->addRelation('UserSc', 'UserSc', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AsignacionScTableMap
