<?php


/**
 * This class defines the structure of the 'grupo_trabajo_sc' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:12
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class GrupoTrabajoScTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.GrupoTrabajoScTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('grupo_trabajo_sc');
		$this->setPhpName('GrupoTrabajoSc');
		$this->setClassname('GrupoTrabajoSc');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 250, null);
		$this->addForeignKey('OWNER_ID', 'OwnerId', 'INTEGER', 'user_sc', 'ID', true, null, null);
		$this->addColumn('FLAG', 'Flag', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATE_AT', 'CreateAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATE_AT', 'UpdateAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('UserSc', 'UserSc', RelationMap::MANY_TO_ONE, array('owner_id' => 'id', ), null, null);
    $this->addRelation('TreeSc', 'TreeSc', RelationMap::ONE_TO_MANY, array('id' => 'grupo_trabajo_id', ), null, null);
    $this->addRelation('DetalleGrupoTrabajoSc', 'DetalleGrupoTrabajoSc', RelationMap::ONE_TO_MANY, array('id' => 'grupo_id', ), null, null);
    $this->addRelation('SolicitudGrupoTrabajoSc', 'SolicitudGrupoTrabajoSc', RelationMap::ONE_TO_MANY, array('id' => 'grupo_id', ), null, null);
    $this->addRelation('AsignacionSc', 'AsignacionSc', RelationMap::ONE_TO_MANY, array('id' => 'grupo_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // GrupoTrabajoScTableMap
