<?php


/**
 * This class defines the structure of the 'user_sc' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:10
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserScTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserScTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('user_sc');
		$this->setPhpName('UserSc');
		$this->setClassname('UserSc');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 50, null);
		$this->addColumn('PROFILE', 'Profile', 'INTEGER', false, null, null);
		$this->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('FLAG', 'Flag', 'LONGVARCHAR', false, null, null);
		$this->addColumn('TOKEN_SESSION', 'TokenSession', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('TreeScRelatedByUserId', 'TreeSc', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('TreeScRelatedByResponsableId', 'TreeSc', RelationMap::ONE_TO_MANY, array('id' => 'responsable_id', ), null, null);
    $this->addRelation('TreeUser', 'TreeUser', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('IndicatorsSc', 'IndicatorsSc', RelationMap::ONE_TO_MANY, array('id' => 'responsable_id', ), null, null);
    $this->addRelation('GrupoTrabajoSc', 'GrupoTrabajoSc', RelationMap::ONE_TO_MANY, array('id' => 'owner_id', ), null, null);
    $this->addRelation('DetalleGrupoTrabajoSc', 'DetalleGrupoTrabajoSc', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('SolicitudGrupoTrabajoSc', 'SolicitudGrupoTrabajoSc', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('AsignacionSc', 'AsignacionSc', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('DataIndicadores', 'DataIndicadores', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // UserScTableMap
