<?php


/**
 * Skeleton subclass for representing a row from the 'solicitud_grupo_trabajo_sc' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/26/11 17:34:51
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SolicitudGrupoTrabajoSc extends BaseSolicitudGrupoTrabajoSc {

} // SolicitudGrupoTrabajoSc
