<?php


/**
 * This class defines the structure of the 'indicators_sc' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:11
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class IndicatorsScTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.IndicatorsScTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('indicators_sc');
		$this->setPhpName('IndicatorsSc');
		$this->setClassname('IndicatorsSc');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('TITULO', 'Titulo', 'VARCHAR', true, 250, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'LONGVARCHAR', false, null, null);
		$this->addColumn('VALOR_MINIMO', 'ValorMinimo', 'INTEGER', false, null, null);
		$this->addColumn('VALOR_DESEADO', 'ValorDeseado', 'INTEGER', false, null, null);
		$this->addColumn('VALOR_OPTIMO', 'ValorOptimo', 'INTEGER', false, null, null);
		$this->addForeignKey('RESPONSABLE_ID', 'ResponsableId', 'INTEGER', 'user_sc', 'ID', false, null, null);
		$this->addForeignKey('TREE_ID', 'TreeId', 'INTEGER', 'tree_sc', 'ID', true, null, null);
		$this->addColumn('PREVIOUS_ID', 'PreviousId', 'INTEGER', false, null, null);
		$this->addColumn('PARENTS', 'Parents', 'LONGVARCHAR', false, null, null);
		$this->addColumn('INDICADORES_HIJOS_CONFIGURE', 'IndicadoresHijosConfigure', 'LONGVARCHAR', false, null, null);
		$this->addColumn('ULTIMO_NODO', 'UltimoNodo', 'VARCHAR', false, 5, null);
		$this->addColumn('VALOR_ACTUAL_ENTREGADO', 'ValorActualEntregado', 'INTEGER', false, null, null);
		$this->addColumn('CONECTORES_CONFIGURE', 'ConectoresConfigure', 'LONGVARCHAR', false, null, null);
		$this->addColumn('OWNER_INDICADORES', 'OwnerIndicadores', 'LONGVARCHAR', false, null, null);
		$this->addColumn('EMAIL_RESPONSABLE', 'EmailResponsable', 'VARCHAR', false, 50, null);
		$this->addColumn('FLAG', 'Flag', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('UserSc', 'UserSc', RelationMap::MANY_TO_ONE, array('responsable_id' => 'id', ), null, null);
    $this->addRelation('TreeSc', 'TreeSc', RelationMap::MANY_TO_ONE, array('tree_id' => 'id', ), null, null);
    $this->addRelation('AsignacionSc', 'AsignacionSc', RelationMap::ONE_TO_MANY, array('id' => 'indicador_id', ), null, null);
    $this->addRelation('DataIndicadores', 'DataIndicadores', RelationMap::ONE_TO_MANY, array('id' => 'indicador_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // IndicatorsScTableMap
