<?php

/**
 * Base class that represents a row from the 'asignacion_sc' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:13
 *
 * @package    lib.model.om
 */
abstract class BaseAsignacionSc extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AsignacionScPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the grupo_id field.
	 * @var        int
	 */
	protected $grupo_id;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the tree_id field.
	 * @var        int
	 */
	protected $tree_id;

	/**
	 * The value for the indicador_id field.
	 * @var        int
	 */
	protected $indicador_id;

	/**
	 * The value for the flag field.
	 * @var        string
	 */
	protected $flag;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the create_at field.
	 * @var        string
	 */
	protected $create_at;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * @var        GrupoTrabajoSc
	 */
	protected $aGrupoTrabajoSc;

	/**
	 * @var        TreeSc
	 */
	protected $aTreeSc;

	/**
	 * @var        IndicatorsSc
	 */
	protected $aIndicatorsSc;

	/**
	 * @var        UserSc
	 */
	protected $aUserSc;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AsignacionScPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [grupo_id] column value.
	 * 
	 * @return     int
	 */
	public function getGrupoId()
	{
		return $this->grupo_id;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [tree_id] column value.
	 * 
	 * @return     int
	 */
	public function getTreeId()
	{
		return $this->tree_id;
	}

	/**
	 * Get the [indicador_id] column value.
	 * 
	 * @return     int
	 */
	public function getIndicadorId()
	{
		return $this->indicador_id;
	}

	/**
	 * Get the [flag] column value.
	 * 
	 * @return     string
	 */
	public function getFlag()
	{
		return $this->flag;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [optionally formatted] temporal [create_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->create_at === null) {
			return null;
		}


		if ($this->create_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->create_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->create_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}


		if ($this->update_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->update_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AsignacionScPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [grupo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setGrupoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->grupo_id !== $v) {
			$this->grupo_id = $v;
			$this->modifiedColumns[] = AsignacionScPeer::GRUPO_ID;
		}

		if ($this->aGrupoTrabajoSc !== null && $this->aGrupoTrabajoSc->getId() !== $v) {
			$this->aGrupoTrabajoSc = null;
		}

		return $this;
	} // setGrupoId()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = AsignacionScPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [tree_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setTreeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_id !== $v) {
			$this->tree_id = $v;
			$this->modifiedColumns[] = AsignacionScPeer::TREE_ID;
		}

		if ($this->aTreeSc !== null && $this->aTreeSc->getId() !== $v) {
			$this->aTreeSc = null;
		}

		return $this;
	} // setTreeId()

	/**
	 * Set the value of [indicador_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setIndicadorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->indicador_id !== $v) {
			$this->indicador_id = $v;
			$this->modifiedColumns[] = AsignacionScPeer::INDICADOR_ID;
		}

		if ($this->aIndicatorsSc !== null && $this->aIndicatorsSc->getId() !== $v) {
			$this->aIndicatorsSc = null;
		}

		return $this;
	} // setIndicadorId()

	/**
	 * Set the value of [flag] column.
	 * 
	 * @param      string $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setFlag($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flag !== $v) {
			$this->flag = $v;
			$this->modifiedColumns[] = AsignacionScPeer::FLAG;
		}

		return $this;
	} // setFlag()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = AsignacionScPeer::USER_ID;
		}

		if ($this->aUserSc !== null && $this->aUserSc->getId() !== $v) {
			$this->aUserSc = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Sets the value of [create_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setCreateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->create_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->create_at !== null && $tmpDt = new DateTime($this->create_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->create_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AsignacionScPeer::CREATE_AT;
			}
		} // if either are not null

		return $this;
	} // setCreateAt()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AsignacionSc The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AsignacionScPeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->grupo_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->email = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tree_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->indicador_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->flag = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->user_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->create_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->update_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = AsignacionScPeer::NUM_COLUMNS - AsignacionScPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AsignacionSc object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aGrupoTrabajoSc !== null && $this->grupo_id !== $this->aGrupoTrabajoSc->getId()) {
			$this->aGrupoTrabajoSc = null;
		}
		if ($this->aTreeSc !== null && $this->tree_id !== $this->aTreeSc->getId()) {
			$this->aTreeSc = null;
		}
		if ($this->aIndicatorsSc !== null && $this->indicador_id !== $this->aIndicatorsSc->getId()) {
			$this->aIndicatorsSc = null;
		}
		if ($this->aUserSc !== null && $this->user_id !== $this->aUserSc->getId()) {
			$this->aUserSc = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AsignacionScPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AsignacionScPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aGrupoTrabajoSc = null;
			$this->aTreeSc = null;
			$this->aIndicatorsSc = null;
			$this->aUserSc = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AsignacionScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAsignacionSc:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AsignacionScPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAsignacionSc:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AsignacionScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAsignacionSc:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAsignacionSc:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AsignacionScPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGrupoTrabajoSc !== null) {
				if ($this->aGrupoTrabajoSc->isModified() || $this->aGrupoTrabajoSc->isNew()) {
					$affectedRows += $this->aGrupoTrabajoSc->save($con);
				}
				$this->setGrupoTrabajoSc($this->aGrupoTrabajoSc);
			}

			if ($this->aTreeSc !== null) {
				if ($this->aTreeSc->isModified() || $this->aTreeSc->isNew()) {
					$affectedRows += $this->aTreeSc->save($con);
				}
				$this->setTreeSc($this->aTreeSc);
			}

			if ($this->aIndicatorsSc !== null) {
				if ($this->aIndicatorsSc->isModified() || $this->aIndicatorsSc->isNew()) {
					$affectedRows += $this->aIndicatorsSc->save($con);
				}
				$this->setIndicatorsSc($this->aIndicatorsSc);
			}

			if ($this->aUserSc !== null) {
				if ($this->aUserSc->isModified() || $this->aUserSc->isNew()) {
					$affectedRows += $this->aUserSc->save($con);
				}
				$this->setUserSc($this->aUserSc);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AsignacionScPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AsignacionScPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AsignacionScPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGrupoTrabajoSc !== null) {
				if (!$this->aGrupoTrabajoSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGrupoTrabajoSc->getValidationFailures());
				}
			}

			if ($this->aTreeSc !== null) {
				if (!$this->aTreeSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTreeSc->getValidationFailures());
				}
			}

			if ($this->aIndicatorsSc !== null) {
				if (!$this->aIndicatorsSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aIndicatorsSc->getValidationFailures());
				}
			}

			if ($this->aUserSc !== null) {
				if (!$this->aUserSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserSc->getValidationFailures());
				}
			}


			if (($retval = AsignacionScPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AsignacionScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getGrupoId();
				break;
			case 2:
				return $this->getEmail();
				break;
			case 3:
				return $this->getTreeId();
				break;
			case 4:
				return $this->getIndicadorId();
				break;
			case 5:
				return $this->getFlag();
				break;
			case 6:
				return $this->getUserId();
				break;
			case 7:
				return $this->getCreateAt();
				break;
			case 8:
				return $this->getUpdateAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AsignacionScPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getGrupoId(),
			$keys[2] => $this->getEmail(),
			$keys[3] => $this->getTreeId(),
			$keys[4] => $this->getIndicadorId(),
			$keys[5] => $this->getFlag(),
			$keys[6] => $this->getUserId(),
			$keys[7] => $this->getCreateAt(),
			$keys[8] => $this->getUpdateAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AsignacionScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setGrupoId($value);
				break;
			case 2:
				$this->setEmail($value);
				break;
			case 3:
				$this->setTreeId($value);
				break;
			case 4:
				$this->setIndicadorId($value);
				break;
			case 5:
				$this->setFlag($value);
				break;
			case 6:
				$this->setUserId($value);
				break;
			case 7:
				$this->setCreateAt($value);
				break;
			case 8:
				$this->setUpdateAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AsignacionScPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setGrupoId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setEmail($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTreeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIndicadorId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFlag($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUserId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreateAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdateAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AsignacionScPeer::DATABASE_NAME);

		if ($this->isColumnModified(AsignacionScPeer::ID)) $criteria->add(AsignacionScPeer::ID, $this->id);
		if ($this->isColumnModified(AsignacionScPeer::GRUPO_ID)) $criteria->add(AsignacionScPeer::GRUPO_ID, $this->grupo_id);
		if ($this->isColumnModified(AsignacionScPeer::EMAIL)) $criteria->add(AsignacionScPeer::EMAIL, $this->email);
		if ($this->isColumnModified(AsignacionScPeer::TREE_ID)) $criteria->add(AsignacionScPeer::TREE_ID, $this->tree_id);
		if ($this->isColumnModified(AsignacionScPeer::INDICADOR_ID)) $criteria->add(AsignacionScPeer::INDICADOR_ID, $this->indicador_id);
		if ($this->isColumnModified(AsignacionScPeer::FLAG)) $criteria->add(AsignacionScPeer::FLAG, $this->flag);
		if ($this->isColumnModified(AsignacionScPeer::USER_ID)) $criteria->add(AsignacionScPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(AsignacionScPeer::CREATE_AT)) $criteria->add(AsignacionScPeer::CREATE_AT, $this->create_at);
		if ($this->isColumnModified(AsignacionScPeer::UPDATE_AT)) $criteria->add(AsignacionScPeer::UPDATE_AT, $this->update_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AsignacionScPeer::DATABASE_NAME);

		$criteria->add(AsignacionScPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AsignacionSc (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setGrupoId($this->grupo_id);

		$copyObj->setEmail($this->email);

		$copyObj->setTreeId($this->tree_id);

		$copyObj->setIndicadorId($this->indicador_id);

		$copyObj->setFlag($this->flag);

		$copyObj->setUserId($this->user_id);

		$copyObj->setCreateAt($this->create_at);

		$copyObj->setUpdateAt($this->update_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AsignacionSc Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AsignacionScPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AsignacionScPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a GrupoTrabajoSc object.
	 *
	 * @param      GrupoTrabajoSc $v
	 * @return     AsignacionSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGrupoTrabajoSc(GrupoTrabajoSc $v = null)
	{
		if ($v === null) {
			$this->setGrupoId(NULL);
		} else {
			$this->setGrupoId($v->getId());
		}

		$this->aGrupoTrabajoSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the GrupoTrabajoSc object, it will not be re-added.
		if ($v !== null) {
			$v->addAsignacionSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated GrupoTrabajoSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     GrupoTrabajoSc The associated GrupoTrabajoSc object.
	 * @throws     PropelException
	 */
	public function getGrupoTrabajoSc(PropelPDO $con = null)
	{
		if ($this->aGrupoTrabajoSc === null && ($this->grupo_id !== null)) {
			$this->aGrupoTrabajoSc = GrupoTrabajoScPeer::retrieveByPk($this->grupo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGrupoTrabajoSc->addAsignacionScs($this);
			 */
		}
		return $this->aGrupoTrabajoSc;
	}

	/**
	 * Declares an association between this object and a TreeSc object.
	 *
	 * @param      TreeSc $v
	 * @return     AsignacionSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTreeSc(TreeSc $v = null)
	{
		if ($v === null) {
			$this->setTreeId(NULL);
		} else {
			$this->setTreeId($v->getId());
		}

		$this->aTreeSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TreeSc object, it will not be re-added.
		if ($v !== null) {
			$v->addAsignacionSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated TreeSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TreeSc The associated TreeSc object.
	 * @throws     PropelException
	 */
	public function getTreeSc(PropelPDO $con = null)
	{
		if ($this->aTreeSc === null && ($this->tree_id !== null)) {
			$this->aTreeSc = TreeScPeer::retrieveByPk($this->tree_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTreeSc->addAsignacionScs($this);
			 */
		}
		return $this->aTreeSc;
	}

	/**
	 * Declares an association between this object and a IndicatorsSc object.
	 *
	 * @param      IndicatorsSc $v
	 * @return     AsignacionSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setIndicatorsSc(IndicatorsSc $v = null)
	{
		if ($v === null) {
			$this->setIndicadorId(NULL);
		} else {
			$this->setIndicadorId($v->getId());
		}

		$this->aIndicatorsSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the IndicatorsSc object, it will not be re-added.
		if ($v !== null) {
			$v->addAsignacionSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated IndicatorsSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     IndicatorsSc The associated IndicatorsSc object.
	 * @throws     PropelException
	 */
	public function getIndicatorsSc(PropelPDO $con = null)
	{
		if ($this->aIndicatorsSc === null && ($this->indicador_id !== null)) {
			$this->aIndicatorsSc = IndicatorsScPeer::retrieveByPk($this->indicador_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aIndicatorsSc->addAsignacionScs($this);
			 */
		}
		return $this->aIndicatorsSc;
	}

	/**
	 * Declares an association between this object and a UserSc object.
	 *
	 * @param      UserSc $v
	 * @return     AsignacionSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserSc(UserSc $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->aUserSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the UserSc object, it will not be re-added.
		if ($v !== null) {
			$v->addAsignacionSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated UserSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     UserSc The associated UserSc object.
	 * @throws     PropelException
	 */
	public function getUserSc(PropelPDO $con = null)
	{
		if ($this->aUserSc === null && ($this->user_id !== null)) {
			$this->aUserSc = UserScPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserSc->addAsignacionScs($this);
			 */
		}
		return $this->aUserSc;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aGrupoTrabajoSc = null;
			$this->aTreeSc = null;
			$this->aIndicatorsSc = null;
			$this->aUserSc = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAsignacionSc:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAsignacionSc::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAsignacionSc
