<?php

/**
 * Base class that represents a row from the 'indicators_sc' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:11
 *
 * @package    lib.model.om
 */
abstract class BaseIndicatorsSc extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        IndicatorsScPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the titulo field.
	 * @var        string
	 */
	protected $titulo;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the valor_minimo field.
	 * @var        int
	 */
	protected $valor_minimo;

	/**
	 * The value for the valor_deseado field.
	 * @var        int
	 */
	protected $valor_deseado;

	/**
	 * The value for the valor_optimo field.
	 * @var        int
	 */
	protected $valor_optimo;

	/**
	 * The value for the responsable_id field.
	 * @var        int
	 */
	protected $responsable_id;

	/**
	 * The value for the tree_id field.
	 * @var        int
	 */
	protected $tree_id;

	/**
	 * The value for the previous_id field.
	 * @var        int
	 */
	protected $previous_id;

	/**
	 * The value for the parents field.
	 * @var        string
	 */
	protected $parents;

	/**
	 * The value for the indicadores_hijos_configure field.
	 * @var        string
	 */
	protected $indicadores_hijos_configure;

	/**
	 * The value for the ultimo_nodo field.
	 * @var        string
	 */
	protected $ultimo_nodo;

	/**
	 * The value for the valor_actual_entregado field.
	 * @var        int
	 */
	protected $valor_actual_entregado;

	/**
	 * The value for the conectores_configure field.
	 * @var        string
	 */
	protected $conectores_configure;

	/**
	 * The value for the owner_indicadores field.
	 * @var        string
	 */
	protected $owner_indicadores;

	/**
	 * The value for the email_responsable field.
	 * @var        string
	 */
	protected $email_responsable;

	/**
	 * The value for the flag field.
	 * @var        string
	 */
	protected $flag;

	/**
	 * @var        UserSc
	 */
	protected $aUserSc;

	/**
	 * @var        TreeSc
	 */
	protected $aTreeSc;

	/**
	 * @var        array AsignacionSc[] Collection to store aggregation of AsignacionSc objects.
	 */
	protected $collAsignacionScs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAsignacionScs.
	 */
	private $lastAsignacionScCriteria = null;

	/**
	 * @var        array DataIndicadores[] Collection to store aggregation of DataIndicadores objects.
	 */
	protected $collDataIndicadoress;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDataIndicadoress.
	 */
	private $lastDataIndicadoresCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'IndicatorsScPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [titulo] column value.
	 * 
	 * @return     string
	 */
	public function getTitulo()
	{
		return $this->titulo;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [valor_minimo] column value.
	 * 
	 * @return     int
	 */
	public function getValorMinimo()
	{
		return $this->valor_minimo;
	}

	/**
	 * Get the [valor_deseado] column value.
	 * 
	 * @return     int
	 */
	public function getValorDeseado()
	{
		return $this->valor_deseado;
	}

	/**
	 * Get the [valor_optimo] column value.
	 * 
	 * @return     int
	 */
	public function getValorOptimo()
	{
		return $this->valor_optimo;
	}

	/**
	 * Get the [responsable_id] column value.
	 * 
	 * @return     int
	 */
	public function getResponsableId()
	{
		return $this->responsable_id;
	}

	/**
	 * Get the [tree_id] column value.
	 * 
	 * @return     int
	 */
	public function getTreeId()
	{
		return $this->tree_id;
	}

	/**
	 * Get the [previous_id] column value.
	 * 
	 * @return     int
	 */
	public function getPreviousId()
	{
		return $this->previous_id;
	}

	/**
	 * Get the [parents] column value.
	 * 
	 * @return     string
	 */
	public function getParents()
	{
		return $this->parents;
	}

	/**
	 * Get the [indicadores_hijos_configure] column value.
	 * 
	 * @return     string
	 */
	public function getIndicadoresHijosConfigure()
	{
		return $this->indicadores_hijos_configure;
	}

	/**
	 * Get the [ultimo_nodo] column value.
	 * 
	 * @return     string
	 */
	public function getUltimoNodo()
	{
		return $this->ultimo_nodo;
	}

	/**
	 * Get the [valor_actual_entregado] column value.
	 * 
	 * @return     int
	 */
	public function getValorActualEntregado()
	{
		return $this->valor_actual_entregado;
	}

	/**
	 * Get the [conectores_configure] column value.
	 * 
	 * @return     string
	 */
	public function getConectoresConfigure()
	{
		return $this->conectores_configure;
	}

	/**
	 * Get the [owner_indicadores] column value.
	 * 
	 * @return     string
	 */
	public function getOwnerIndicadores()
	{
		return $this->owner_indicadores;
	}

	/**
	 * Get the [email_responsable] column value.
	 * 
	 * @return     string
	 */
	public function getEmailResponsable()
	{
		return $this->email_responsable;
	}

	/**
	 * Get the [flag] column value.
	 * 
	 * @return     string
	 */
	public function getFlag()
	{
		return $this->flag;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [titulo] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setTitulo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titulo !== $v) {
			$this->titulo = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::TITULO;
		}

		return $this;
	} // setTitulo()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [valor_minimo] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setValorMinimo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_minimo !== $v) {
			$this->valor_minimo = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::VALOR_MINIMO;
		}

		return $this;
	} // setValorMinimo()

	/**
	 * Set the value of [valor_deseado] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setValorDeseado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_deseado !== $v) {
			$this->valor_deseado = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::VALOR_DESEADO;
		}

		return $this;
	} // setValorDeseado()

	/**
	 * Set the value of [valor_optimo] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setValorOptimo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_optimo !== $v) {
			$this->valor_optimo = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::VALOR_OPTIMO;
		}

		return $this;
	} // setValorOptimo()

	/**
	 * Set the value of [responsable_id] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setResponsableId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->responsable_id !== $v) {
			$this->responsable_id = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::RESPONSABLE_ID;
		}

		if ($this->aUserSc !== null && $this->aUserSc->getId() !== $v) {
			$this->aUserSc = null;
		}

		return $this;
	} // setResponsableId()

	/**
	 * Set the value of [tree_id] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setTreeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_id !== $v) {
			$this->tree_id = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::TREE_ID;
		}

		if ($this->aTreeSc !== null && $this->aTreeSc->getId() !== $v) {
			$this->aTreeSc = null;
		}

		return $this;
	} // setTreeId()

	/**
	 * Set the value of [previous_id] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setPreviousId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->previous_id !== $v) {
			$this->previous_id = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::PREVIOUS_ID;
		}

		return $this;
	} // setPreviousId()

	/**
	 * Set the value of [parents] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setParents($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parents !== $v) {
			$this->parents = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::PARENTS;
		}

		return $this;
	} // setParents()

	/**
	 * Set the value of [indicadores_hijos_configure] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setIndicadoresHijosConfigure($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->indicadores_hijos_configure !== $v) {
			$this->indicadores_hijos_configure = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::INDICADORES_HIJOS_CONFIGURE;
		}

		return $this;
	} // setIndicadoresHijosConfigure()

	/**
	 * Set the value of [ultimo_nodo] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setUltimoNodo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ultimo_nodo !== $v) {
			$this->ultimo_nodo = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::ULTIMO_NODO;
		}

		return $this;
	} // setUltimoNodo()

	/**
	 * Set the value of [valor_actual_entregado] column.
	 * 
	 * @param      int $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setValorActualEntregado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_actual_entregado !== $v) {
			$this->valor_actual_entregado = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::VALOR_ACTUAL_ENTREGADO;
		}

		return $this;
	} // setValorActualEntregado()

	/**
	 * Set the value of [conectores_configure] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setConectoresConfigure($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conectores_configure !== $v) {
			$this->conectores_configure = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::CONECTORES_CONFIGURE;
		}

		return $this;
	} // setConectoresConfigure()

	/**
	 * Set the value of [owner_indicadores] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setOwnerIndicadores($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->owner_indicadores !== $v) {
			$this->owner_indicadores = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::OWNER_INDICADORES;
		}

		return $this;
	} // setOwnerIndicadores()

	/**
	 * Set the value of [email_responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setEmailResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email_responsable !== $v) {
			$this->email_responsable = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::EMAIL_RESPONSABLE;
		}

		return $this;
	} // setEmailResponsable()

	/**
	 * Set the value of [flag] column.
	 * 
	 * @param      string $v new value
	 * @return     IndicatorsSc The current object (for fluent API support)
	 */
	public function setFlag($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flag !== $v) {
			$this->flag = $v;
			$this->modifiedColumns[] = IndicatorsScPeer::FLAG;
		}

		return $this;
	} // setFlag()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->titulo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->descripcion = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->valor_minimo = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->valor_deseado = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->valor_optimo = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->responsable_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->tree_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->previous_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->parents = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->indicadores_hijos_configure = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->ultimo_nodo = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->valor_actual_entregado = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->conectores_configure = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->owner_indicadores = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->email_responsable = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->flag = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = IndicatorsScPeer::NUM_COLUMNS - IndicatorsScPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating IndicatorsSc object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUserSc !== null && $this->responsable_id !== $this->aUserSc->getId()) {
			$this->aUserSc = null;
		}
		if ($this->aTreeSc !== null && $this->tree_id !== $this->aTreeSc->getId()) {
			$this->aTreeSc = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IndicatorsScPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = IndicatorsScPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUserSc = null;
			$this->aTreeSc = null;
			$this->collAsignacionScs = null;
			$this->lastAsignacionScCriteria = null;

			$this->collDataIndicadoress = null;
			$this->lastDataIndicadoresCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IndicatorsScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseIndicatorsSc:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				IndicatorsScPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseIndicatorsSc:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IndicatorsScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseIndicatorsSc:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseIndicatorsSc:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				IndicatorsScPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUserSc !== null) {
				if ($this->aUserSc->isModified() || $this->aUserSc->isNew()) {
					$affectedRows += $this->aUserSc->save($con);
				}
				$this->setUserSc($this->aUserSc);
			}

			if ($this->aTreeSc !== null) {
				if ($this->aTreeSc->isModified() || $this->aTreeSc->isNew()) {
					$affectedRows += $this->aTreeSc->save($con);
				}
				$this->setTreeSc($this->aTreeSc);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = IndicatorsScPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = IndicatorsScPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += IndicatorsScPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAsignacionScs !== null) {
				foreach ($this->collAsignacionScs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDataIndicadoress !== null) {
				foreach ($this->collDataIndicadoress as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUserSc !== null) {
				if (!$this->aUserSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserSc->getValidationFailures());
				}
			}

			if ($this->aTreeSc !== null) {
				if (!$this->aTreeSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTreeSc->getValidationFailures());
				}
			}


			if (($retval = IndicatorsScPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAsignacionScs !== null) {
					foreach ($this->collAsignacionScs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDataIndicadoress !== null) {
					foreach ($this->collDataIndicadoress as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = IndicatorsScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTitulo();
				break;
			case 2:
				return $this->getDescripcion();
				break;
			case 3:
				return $this->getValorMinimo();
				break;
			case 4:
				return $this->getValorDeseado();
				break;
			case 5:
				return $this->getValorOptimo();
				break;
			case 6:
				return $this->getResponsableId();
				break;
			case 7:
				return $this->getTreeId();
				break;
			case 8:
				return $this->getPreviousId();
				break;
			case 9:
				return $this->getParents();
				break;
			case 10:
				return $this->getIndicadoresHijosConfigure();
				break;
			case 11:
				return $this->getUltimoNodo();
				break;
			case 12:
				return $this->getValorActualEntregado();
				break;
			case 13:
				return $this->getConectoresConfigure();
				break;
			case 14:
				return $this->getOwnerIndicadores();
				break;
			case 15:
				return $this->getEmailResponsable();
				break;
			case 16:
				return $this->getFlag();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = IndicatorsScPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTitulo(),
			$keys[2] => $this->getDescripcion(),
			$keys[3] => $this->getValorMinimo(),
			$keys[4] => $this->getValorDeseado(),
			$keys[5] => $this->getValorOptimo(),
			$keys[6] => $this->getResponsableId(),
			$keys[7] => $this->getTreeId(),
			$keys[8] => $this->getPreviousId(),
			$keys[9] => $this->getParents(),
			$keys[10] => $this->getIndicadoresHijosConfigure(),
			$keys[11] => $this->getUltimoNodo(),
			$keys[12] => $this->getValorActualEntregado(),
			$keys[13] => $this->getConectoresConfigure(),
			$keys[14] => $this->getOwnerIndicadores(),
			$keys[15] => $this->getEmailResponsable(),
			$keys[16] => $this->getFlag(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = IndicatorsScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTitulo($value);
				break;
			case 2:
				$this->setDescripcion($value);
				break;
			case 3:
				$this->setValorMinimo($value);
				break;
			case 4:
				$this->setValorDeseado($value);
				break;
			case 5:
				$this->setValorOptimo($value);
				break;
			case 6:
				$this->setResponsableId($value);
				break;
			case 7:
				$this->setTreeId($value);
				break;
			case 8:
				$this->setPreviousId($value);
				break;
			case 9:
				$this->setParents($value);
				break;
			case 10:
				$this->setIndicadoresHijosConfigure($value);
				break;
			case 11:
				$this->setUltimoNodo($value);
				break;
			case 12:
				$this->setValorActualEntregado($value);
				break;
			case 13:
				$this->setConectoresConfigure($value);
				break;
			case 14:
				$this->setOwnerIndicadores($value);
				break;
			case 15:
				$this->setEmailResponsable($value);
				break;
			case 16:
				$this->setFlag($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = IndicatorsScPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTitulo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescripcion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setValorMinimo($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setValorDeseado($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setValorOptimo($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setResponsableId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTreeId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPreviousId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setParents($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIndicadoresHijosConfigure($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUltimoNodo($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setValorActualEntregado($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setConectoresConfigure($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setOwnerIndicadores($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setEmailResponsable($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setFlag($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);

		if ($this->isColumnModified(IndicatorsScPeer::ID)) $criteria->add(IndicatorsScPeer::ID, $this->id);
		if ($this->isColumnModified(IndicatorsScPeer::TITULO)) $criteria->add(IndicatorsScPeer::TITULO, $this->titulo);
		if ($this->isColumnModified(IndicatorsScPeer::DESCRIPCION)) $criteria->add(IndicatorsScPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(IndicatorsScPeer::VALOR_MINIMO)) $criteria->add(IndicatorsScPeer::VALOR_MINIMO, $this->valor_minimo);
		if ($this->isColumnModified(IndicatorsScPeer::VALOR_DESEADO)) $criteria->add(IndicatorsScPeer::VALOR_DESEADO, $this->valor_deseado);
		if ($this->isColumnModified(IndicatorsScPeer::VALOR_OPTIMO)) $criteria->add(IndicatorsScPeer::VALOR_OPTIMO, $this->valor_optimo);
		if ($this->isColumnModified(IndicatorsScPeer::RESPONSABLE_ID)) $criteria->add(IndicatorsScPeer::RESPONSABLE_ID, $this->responsable_id);
		if ($this->isColumnModified(IndicatorsScPeer::TREE_ID)) $criteria->add(IndicatorsScPeer::TREE_ID, $this->tree_id);
		if ($this->isColumnModified(IndicatorsScPeer::PREVIOUS_ID)) $criteria->add(IndicatorsScPeer::PREVIOUS_ID, $this->previous_id);
		if ($this->isColumnModified(IndicatorsScPeer::PARENTS)) $criteria->add(IndicatorsScPeer::PARENTS, $this->parents);
		if ($this->isColumnModified(IndicatorsScPeer::INDICADORES_HIJOS_CONFIGURE)) $criteria->add(IndicatorsScPeer::INDICADORES_HIJOS_CONFIGURE, $this->indicadores_hijos_configure);
		if ($this->isColumnModified(IndicatorsScPeer::ULTIMO_NODO)) $criteria->add(IndicatorsScPeer::ULTIMO_NODO, $this->ultimo_nodo);
		if ($this->isColumnModified(IndicatorsScPeer::VALOR_ACTUAL_ENTREGADO)) $criteria->add(IndicatorsScPeer::VALOR_ACTUAL_ENTREGADO, $this->valor_actual_entregado);
		if ($this->isColumnModified(IndicatorsScPeer::CONECTORES_CONFIGURE)) $criteria->add(IndicatorsScPeer::CONECTORES_CONFIGURE, $this->conectores_configure);
		if ($this->isColumnModified(IndicatorsScPeer::OWNER_INDICADORES)) $criteria->add(IndicatorsScPeer::OWNER_INDICADORES, $this->owner_indicadores);
		if ($this->isColumnModified(IndicatorsScPeer::EMAIL_RESPONSABLE)) $criteria->add(IndicatorsScPeer::EMAIL_RESPONSABLE, $this->email_responsable);
		if ($this->isColumnModified(IndicatorsScPeer::FLAG)) $criteria->add(IndicatorsScPeer::FLAG, $this->flag);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);

		$criteria->add(IndicatorsScPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of IndicatorsSc (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTitulo($this->titulo);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setValorMinimo($this->valor_minimo);

		$copyObj->setValorDeseado($this->valor_deseado);

		$copyObj->setValorOptimo($this->valor_optimo);

		$copyObj->setResponsableId($this->responsable_id);

		$copyObj->setTreeId($this->tree_id);

		$copyObj->setPreviousId($this->previous_id);

		$copyObj->setParents($this->parents);

		$copyObj->setIndicadoresHijosConfigure($this->indicadores_hijos_configure);

		$copyObj->setUltimoNodo($this->ultimo_nodo);

		$copyObj->setValorActualEntregado($this->valor_actual_entregado);

		$copyObj->setConectoresConfigure($this->conectores_configure);

		$copyObj->setOwnerIndicadores($this->owner_indicadores);

		$copyObj->setEmailResponsable($this->email_responsable);

		$copyObj->setFlag($this->flag);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAsignacionScs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAsignacionSc($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDataIndicadoress() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDataIndicadores($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     IndicatorsSc Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     IndicatorsScPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new IndicatorsScPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a UserSc object.
	 *
	 * @param      UserSc $v
	 * @return     IndicatorsSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserSc(UserSc $v = null)
	{
		if ($v === null) {
			$this->setResponsableId(NULL);
		} else {
			$this->setResponsableId($v->getId());
		}

		$this->aUserSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the UserSc object, it will not be re-added.
		if ($v !== null) {
			$v->addIndicatorsSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated UserSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     UserSc The associated UserSc object.
	 * @throws     PropelException
	 */
	public function getUserSc(PropelPDO $con = null)
	{
		if ($this->aUserSc === null && ($this->responsable_id !== null)) {
			$this->aUserSc = UserScPeer::retrieveByPk($this->responsable_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserSc->addIndicatorsScs($this);
			 */
		}
		return $this->aUserSc;
	}

	/**
	 * Declares an association between this object and a TreeSc object.
	 *
	 * @param      TreeSc $v
	 * @return     IndicatorsSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTreeSc(TreeSc $v = null)
	{
		if ($v === null) {
			$this->setTreeId(NULL);
		} else {
			$this->setTreeId($v->getId());
		}

		$this->aTreeSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TreeSc object, it will not be re-added.
		if ($v !== null) {
			$v->addIndicatorsSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated TreeSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TreeSc The associated TreeSc object.
	 * @throws     PropelException
	 */
	public function getTreeSc(PropelPDO $con = null)
	{
		if ($this->aTreeSc === null && ($this->tree_id !== null)) {
			$this->aTreeSc = TreeScPeer::retrieveByPk($this->tree_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTreeSc->addIndicatorsScs($this);
			 */
		}
		return $this->aTreeSc;
	}

	/**
	 * Clears out the collAsignacionScs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAsignacionScs()
	 */
	public function clearAsignacionScs()
	{
		$this->collAsignacionScs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAsignacionScs collection (array).
	 *
	 * By default this just sets the collAsignacionScs collection to an empty array (like clearcollAsignacionScs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAsignacionScs()
	{
		$this->collAsignacionScs = array();
	}

	/**
	 * Gets an array of AsignacionSc objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc has previously been saved, it will retrieve
	 * related AsignacionScs from storage. If this IndicatorsSc is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AsignacionSc[]
	 * @throws     PropelException
	 */
	public function getAsignacionScs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
			   $this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				AsignacionScPeer::addSelectColumns($criteria);
				$this->collAsignacionScs = AsignacionScPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				AsignacionScPeer::addSelectColumns($criteria);
				if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
					$this->collAsignacionScs = AsignacionScPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAsignacionScCriteria = $criteria;
		return $this->collAsignacionScs;
	}

	/**
	 * Returns the number of related AsignacionSc objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AsignacionSc objects.
	 * @throws     PropelException
	 */
	public function countAsignacionScs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				$count = AsignacionScPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
					$count = AsignacionScPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAsignacionScs);
				}
			} else {
				$count = count($this->collAsignacionScs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AsignacionSc object to this object
	 * through the AsignacionSc foreign key attribute.
	 *
	 * @param      AsignacionSc $l AsignacionSc
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAsignacionSc(AsignacionSc $l)
	{
		if ($this->collAsignacionScs === null) {
			$this->initAsignacionScs();
		}
		if (!in_array($l, $this->collAsignacionScs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAsignacionScs, $l);
			$l->setIndicatorsSc($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc is new, it will return
	 * an empty collection; or if this IndicatorsSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in IndicatorsSc.
	 */
	public function getAsignacionScsJoinGrupoTrabajoSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinGrupoTrabajoSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinGrupoTrabajoSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc is new, it will return
	 * an empty collection; or if this IndicatorsSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in IndicatorsSc.
	 */
	public function getAsignacionScsJoinTreeSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinTreeSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinTreeSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc is new, it will return
	 * an empty collection; or if this IndicatorsSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in IndicatorsSc.
	 */
	public function getAsignacionScsJoinUserSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::INDICADOR_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}

	/**
	 * Clears out the collDataIndicadoress collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDataIndicadoress()
	 */
	public function clearDataIndicadoress()
	{
		$this->collDataIndicadoress = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDataIndicadoress collection (array).
	 *
	 * By default this just sets the collDataIndicadoress collection to an empty array (like clearcollDataIndicadoress());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDataIndicadoress()
	{
		$this->collDataIndicadoress = array();
	}

	/**
	 * Gets an array of DataIndicadores objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc has previously been saved, it will retrieve
	 * related DataIndicadoress from storage. If this IndicatorsSc is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DataIndicadores[]
	 * @throws     PropelException
	 */
	public function getDataIndicadoress($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDataIndicadoress === null) {
			if ($this->isNew()) {
			   $this->collDataIndicadoress = array();
			} else {

				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				DataIndicadoresPeer::addSelectColumns($criteria);
				$this->collDataIndicadoress = DataIndicadoresPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				DataIndicadoresPeer::addSelectColumns($criteria);
				if (!isset($this->lastDataIndicadoresCriteria) || !$this->lastDataIndicadoresCriteria->equals($criteria)) {
					$this->collDataIndicadoress = DataIndicadoresPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDataIndicadoresCriteria = $criteria;
		return $this->collDataIndicadoress;
	}

	/**
	 * Returns the number of related DataIndicadores objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DataIndicadores objects.
	 * @throws     PropelException
	 */
	public function countDataIndicadoress(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDataIndicadoress === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				$count = DataIndicadoresPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				if (!isset($this->lastDataIndicadoresCriteria) || !$this->lastDataIndicadoresCriteria->equals($criteria)) {
					$count = DataIndicadoresPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDataIndicadoress);
				}
			} else {
				$count = count($this->collDataIndicadoress);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DataIndicadores object to this object
	 * through the DataIndicadores foreign key attribute.
	 *
	 * @param      DataIndicadores $l DataIndicadores
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDataIndicadores(DataIndicadores $l)
	{
		if ($this->collDataIndicadoress === null) {
			$this->initDataIndicadoress();
		}
		if (!in_array($l, $this->collDataIndicadoress, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDataIndicadoress, $l);
			$l->setIndicatorsSc($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc is new, it will return
	 * an empty collection; or if this IndicatorsSc has previously
	 * been saved, it will retrieve related DataIndicadoress from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in IndicatorsSc.
	 */
	public function getDataIndicadoressJoinUserSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDataIndicadoress === null) {
			if ($this->isNew()) {
				$this->collDataIndicadoress = array();
			} else {

				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				$this->collDataIndicadoress = DataIndicadoresPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

			if (!isset($this->lastDataIndicadoresCriteria) || !$this->lastDataIndicadoresCriteria->equals($criteria)) {
				$this->collDataIndicadoress = DataIndicadoresPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastDataIndicadoresCriteria = $criteria;

		return $this->collDataIndicadoress;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this IndicatorsSc is new, it will return
	 * an empty collection; or if this IndicatorsSc has previously
	 * been saved, it will retrieve related DataIndicadoress from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in IndicatorsSc.
	 */
	public function getDataIndicadoressJoinGroupDataIndicadores($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(IndicatorsScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDataIndicadoress === null) {
			if ($this->isNew()) {
				$this->collDataIndicadoress = array();
			} else {

				$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

				$this->collDataIndicadoress = DataIndicadoresPeer::doSelectJoinGroupDataIndicadores($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DataIndicadoresPeer::INDICADOR_ID, $this->id);

			if (!isset($this->lastDataIndicadoresCriteria) || !$this->lastDataIndicadoresCriteria->equals($criteria)) {
				$this->collDataIndicadoress = DataIndicadoresPeer::doSelectJoinGroupDataIndicadores($criteria, $con, $join_behavior);
			}
		}
		$this->lastDataIndicadoresCriteria = $criteria;

		return $this->collDataIndicadoress;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAsignacionScs) {
				foreach ((array) $this->collAsignacionScs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDataIndicadoress) {
				foreach ((array) $this->collDataIndicadoress as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAsignacionScs = null;
		$this->collDataIndicadoress = null;
			$this->aUserSc = null;
			$this->aTreeSc = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseIndicatorsSc:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseIndicatorsSc::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseIndicatorsSc
