<?php

/**
 * Base class that represents a row from the 'tmp_data_reports' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:14
 *
 * @package    lib.model.om
 */
abstract class BaseTmpDataReports extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TmpDataReportsPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the indicador_id field.
	 * @var        int
	 */
	protected $indicador_id;

	/**
	 * The value for the valor_minimo field.
	 * @var        int
	 */
	protected $valor_minimo;

	/**
	 * The value for the valor_deseado field.
	 * @var        int
	 */
	protected $valor_deseado;

	/**
	 * The value for the valor_optimo field.
	 * @var        int
	 */
	protected $valor_optimo;

	/**
	 * The value for the tree_id field.
	 * @var        int
	 */
	protected $tree_id;

	/**
	 * The value for the previous_id field.
	 * @var        int
	 */
	protected $previous_id;

	/**
	 * The value for the parents field.
	 * @var        string
	 */
	protected $parents;

	/**
	 * The value for the indicadores_hijos_configure field.
	 * @var        string
	 */
	protected $indicadores_hijos_configure;

	/**
	 * The value for the ultimo_nodo field.
	 * @var        string
	 */
	protected $ultimo_nodo;

	/**
	 * The value for the data field.
	 * @var        int
	 */
	protected $data;

	/**
	 * The value for the conectores_configure field.
	 * @var        string
	 */
	protected $conectores_configure;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * The value for the flag field.
	 * @var        string
	 */
	protected $flag;

	/**
	 * @var        TmpTreeSc
	 */
	protected $aTmpTreeSc;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TmpDataReportsPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [indicador_id] column value.
	 * 
	 * @return     int
	 */
	public function getIndicadorId()
	{
		return $this->indicador_id;
	}

	/**
	 * Get the [valor_minimo] column value.
	 * 
	 * @return     int
	 */
	public function getValorMinimo()
	{
		return $this->valor_minimo;
	}

	/**
	 * Get the [valor_deseado] column value.
	 * 
	 * @return     int
	 */
	public function getValorDeseado()
	{
		return $this->valor_deseado;
	}

	/**
	 * Get the [valor_optimo] column value.
	 * 
	 * @return     int
	 */
	public function getValorOptimo()
	{
		return $this->valor_optimo;
	}

	/**
	 * Get the [tree_id] column value.
	 * 
	 * @return     int
	 */
	public function getTreeId()
	{
		return $this->tree_id;
	}

	/**
	 * Get the [previous_id] column value.
	 * 
	 * @return     int
	 */
	public function getPreviousId()
	{
		return $this->previous_id;
	}

	/**
	 * Get the [parents] column value.
	 * 
	 * @return     string
	 */
	public function getParents()
	{
		return $this->parents;
	}

	/**
	 * Get the [indicadores_hijos_configure] column value.
	 * 
	 * @return     string
	 */
	public function getIndicadoresHijosConfigure()
	{
		return $this->indicadores_hijos_configure;
	}

	/**
	 * Get the [ultimo_nodo] column value.
	 * 
	 * @return     string
	 */
	public function getUltimoNodo()
	{
		return $this->ultimo_nodo;
	}

	/**
	 * Get the [data] column value.
	 * 
	 * @return     int
	 */
	public function getData()
	{
		return $this->data;
	}

	/**
	 * Get the [conectores_configure] column value.
	 * 
	 * @return     string
	 */
	public function getConectoresConfigure()
	{
		return $this->conectores_configure;
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}


		if ($this->update_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->update_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [flag] column value.
	 * 
	 * @return     string
	 */
	public function getFlag()
	{
		return $this->flag;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [indicador_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setIndicadorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->indicador_id !== $v) {
			$this->indicador_id = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::INDICADOR_ID;
		}

		return $this;
	} // setIndicadorId()

	/**
	 * Set the value of [valor_minimo] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setValorMinimo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_minimo !== $v) {
			$this->valor_minimo = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::VALOR_MINIMO;
		}

		return $this;
	} // setValorMinimo()

	/**
	 * Set the value of [valor_deseado] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setValorDeseado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_deseado !== $v) {
			$this->valor_deseado = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::VALOR_DESEADO;
		}

		return $this;
	} // setValorDeseado()

	/**
	 * Set the value of [valor_optimo] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setValorOptimo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_optimo !== $v) {
			$this->valor_optimo = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::VALOR_OPTIMO;
		}

		return $this;
	} // setValorOptimo()

	/**
	 * Set the value of [tree_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setTreeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_id !== $v) {
			$this->tree_id = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::TREE_ID;
		}

		if ($this->aTmpTreeSc !== null && $this->aTmpTreeSc->getId() !== $v) {
			$this->aTmpTreeSc = null;
		}

		return $this;
	} // setTreeId()

	/**
	 * Set the value of [previous_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setPreviousId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->previous_id !== $v) {
			$this->previous_id = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::PREVIOUS_ID;
		}

		return $this;
	} // setPreviousId()

	/**
	 * Set the value of [parents] column.
	 * 
	 * @param      string $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setParents($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parents !== $v) {
			$this->parents = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::PARENTS;
		}

		return $this;
	} // setParents()

	/**
	 * Set the value of [indicadores_hijos_configure] column.
	 * 
	 * @param      string $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setIndicadoresHijosConfigure($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->indicadores_hijos_configure !== $v) {
			$this->indicadores_hijos_configure = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::INDICADORES_HIJOS_CONFIGURE;
		}

		return $this;
	} // setIndicadoresHijosConfigure()

	/**
	 * Set the value of [ultimo_nodo] column.
	 * 
	 * @param      string $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setUltimoNodo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ultimo_nodo !== $v) {
			$this->ultimo_nodo = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::ULTIMO_NODO;
		}

		return $this;
	} // setUltimoNodo()

	/**
	 * Set the value of [data] column.
	 * 
	 * @param      int $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setData($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->data !== $v) {
			$this->data = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::DATA;
		}

		return $this;
	} // setData()

	/**
	 * Set the value of [conectores_configure] column.
	 * 
	 * @param      string $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setConectoresConfigure($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conectores_configure !== $v) {
			$this->conectores_configure = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::CONECTORES_CONFIGURE;
		}

		return $this;
	} // setConectoresConfigure()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TmpDataReportsPeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Set the value of [flag] column.
	 * 
	 * @param      string $v new value
	 * @return     TmpDataReports The current object (for fluent API support)
	 */
	public function setFlag($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flag !== $v) {
			$this->flag = $v;
			$this->modifiedColumns[] = TmpDataReportsPeer::FLAG;
		}

		return $this;
	} // setFlag()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->indicador_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->valor_minimo = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->valor_deseado = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->valor_optimo = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->tree_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->previous_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->parents = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->indicadores_hijos_configure = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ultimo_nodo = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->data = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->conectores_configure = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->update_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->flag = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = TmpDataReportsPeer::NUM_COLUMNS - TmpDataReportsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating TmpDataReports object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTmpTreeSc !== null && $this->tree_id !== $this->aTmpTreeSc->getId()) {
			$this->aTmpTreeSc = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TmpDataReportsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TmpDataReportsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTmpTreeSc = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TmpDataReportsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTmpDataReports:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				TmpDataReportsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTmpDataReports:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TmpDataReportsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTmpDataReports:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTmpDataReports:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TmpDataReportsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTmpTreeSc !== null) {
				if ($this->aTmpTreeSc->isModified() || $this->aTmpTreeSc->isNew()) {
					$affectedRows += $this->aTmpTreeSc->save($con);
				}
				$this->setTmpTreeSc($this->aTmpTreeSc);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TmpDataReportsPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TmpDataReportsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TmpDataReportsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTmpTreeSc !== null) {
				if (!$this->aTmpTreeSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTmpTreeSc->getValidationFailures());
				}
			}


			if (($retval = TmpDataReportsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TmpDataReportsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIndicadorId();
				break;
			case 2:
				return $this->getValorMinimo();
				break;
			case 3:
				return $this->getValorDeseado();
				break;
			case 4:
				return $this->getValorOptimo();
				break;
			case 5:
				return $this->getTreeId();
				break;
			case 6:
				return $this->getPreviousId();
				break;
			case 7:
				return $this->getParents();
				break;
			case 8:
				return $this->getIndicadoresHijosConfigure();
				break;
			case 9:
				return $this->getUltimoNodo();
				break;
			case 10:
				return $this->getData();
				break;
			case 11:
				return $this->getConectoresConfigure();
				break;
			case 12:
				return $this->getUpdateAt();
				break;
			case 13:
				return $this->getFlag();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TmpDataReportsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIndicadorId(),
			$keys[2] => $this->getValorMinimo(),
			$keys[3] => $this->getValorDeseado(),
			$keys[4] => $this->getValorOptimo(),
			$keys[5] => $this->getTreeId(),
			$keys[6] => $this->getPreviousId(),
			$keys[7] => $this->getParents(),
			$keys[8] => $this->getIndicadoresHijosConfigure(),
			$keys[9] => $this->getUltimoNodo(),
			$keys[10] => $this->getData(),
			$keys[11] => $this->getConectoresConfigure(),
			$keys[12] => $this->getUpdateAt(),
			$keys[13] => $this->getFlag(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TmpDataReportsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIndicadorId($value);
				break;
			case 2:
				$this->setValorMinimo($value);
				break;
			case 3:
				$this->setValorDeseado($value);
				break;
			case 4:
				$this->setValorOptimo($value);
				break;
			case 5:
				$this->setTreeId($value);
				break;
			case 6:
				$this->setPreviousId($value);
				break;
			case 7:
				$this->setParents($value);
				break;
			case 8:
				$this->setIndicadoresHijosConfigure($value);
				break;
			case 9:
				$this->setUltimoNodo($value);
				break;
			case 10:
				$this->setData($value);
				break;
			case 11:
				$this->setConectoresConfigure($value);
				break;
			case 12:
				$this->setUpdateAt($value);
				break;
			case 13:
				$this->setFlag($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TmpDataReportsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIndicadorId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setValorMinimo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setValorDeseado($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setValorOptimo($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTreeId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPreviousId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setParents($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIndicadoresHijosConfigure($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUltimoNodo($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setData($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setConectoresConfigure($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUpdateAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setFlag($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TmpDataReportsPeer::DATABASE_NAME);

		if ($this->isColumnModified(TmpDataReportsPeer::ID)) $criteria->add(TmpDataReportsPeer::ID, $this->id);
		if ($this->isColumnModified(TmpDataReportsPeer::INDICADOR_ID)) $criteria->add(TmpDataReportsPeer::INDICADOR_ID, $this->indicador_id);
		if ($this->isColumnModified(TmpDataReportsPeer::VALOR_MINIMO)) $criteria->add(TmpDataReportsPeer::VALOR_MINIMO, $this->valor_minimo);
		if ($this->isColumnModified(TmpDataReportsPeer::VALOR_DESEADO)) $criteria->add(TmpDataReportsPeer::VALOR_DESEADO, $this->valor_deseado);
		if ($this->isColumnModified(TmpDataReportsPeer::VALOR_OPTIMO)) $criteria->add(TmpDataReportsPeer::VALOR_OPTIMO, $this->valor_optimo);
		if ($this->isColumnModified(TmpDataReportsPeer::TREE_ID)) $criteria->add(TmpDataReportsPeer::TREE_ID, $this->tree_id);
		if ($this->isColumnModified(TmpDataReportsPeer::PREVIOUS_ID)) $criteria->add(TmpDataReportsPeer::PREVIOUS_ID, $this->previous_id);
		if ($this->isColumnModified(TmpDataReportsPeer::PARENTS)) $criteria->add(TmpDataReportsPeer::PARENTS, $this->parents);
		if ($this->isColumnModified(TmpDataReportsPeer::INDICADORES_HIJOS_CONFIGURE)) $criteria->add(TmpDataReportsPeer::INDICADORES_HIJOS_CONFIGURE, $this->indicadores_hijos_configure);
		if ($this->isColumnModified(TmpDataReportsPeer::ULTIMO_NODO)) $criteria->add(TmpDataReportsPeer::ULTIMO_NODO, $this->ultimo_nodo);
		if ($this->isColumnModified(TmpDataReportsPeer::DATA)) $criteria->add(TmpDataReportsPeer::DATA, $this->data);
		if ($this->isColumnModified(TmpDataReportsPeer::CONECTORES_CONFIGURE)) $criteria->add(TmpDataReportsPeer::CONECTORES_CONFIGURE, $this->conectores_configure);
		if ($this->isColumnModified(TmpDataReportsPeer::UPDATE_AT)) $criteria->add(TmpDataReportsPeer::UPDATE_AT, $this->update_at);
		if ($this->isColumnModified(TmpDataReportsPeer::FLAG)) $criteria->add(TmpDataReportsPeer::FLAG, $this->flag);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TmpDataReportsPeer::DATABASE_NAME);

		$criteria->add(TmpDataReportsPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of TmpDataReports (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIndicadorId($this->indicador_id);

		$copyObj->setValorMinimo($this->valor_minimo);

		$copyObj->setValorDeseado($this->valor_deseado);

		$copyObj->setValorOptimo($this->valor_optimo);

		$copyObj->setTreeId($this->tree_id);

		$copyObj->setPreviousId($this->previous_id);

		$copyObj->setParents($this->parents);

		$copyObj->setIndicadoresHijosConfigure($this->indicadores_hijos_configure);

		$copyObj->setUltimoNodo($this->ultimo_nodo);

		$copyObj->setData($this->data);

		$copyObj->setConectoresConfigure($this->conectores_configure);

		$copyObj->setUpdateAt($this->update_at);

		$copyObj->setFlag($this->flag);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     TmpDataReports Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TmpDataReportsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TmpDataReportsPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a TmpTreeSc object.
	 *
	 * @param      TmpTreeSc $v
	 * @return     TmpDataReports The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTmpTreeSc(TmpTreeSc $v = null)
	{
		if ($v === null) {
			$this->setTreeId(NULL);
		} else {
			$this->setTreeId($v->getId());
		}

		$this->aTmpTreeSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TmpTreeSc object, it will not be re-added.
		if ($v !== null) {
			$v->addTmpDataReports($this);
		}

		return $this;
	}


	/**
	 * Get the associated TmpTreeSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TmpTreeSc The associated TmpTreeSc object.
	 * @throws     PropelException
	 */
	public function getTmpTreeSc(PropelPDO $con = null)
	{
		if ($this->aTmpTreeSc === null && ($this->tree_id !== null)) {
			$this->aTmpTreeSc = TmpTreeScPeer::retrieveByPk($this->tree_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTmpTreeSc->addTmpDataReportss($this);
			 */
		}
		return $this->aTmpTreeSc;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aTmpTreeSc = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTmpDataReports:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTmpDataReports::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTmpDataReports
