<?php

/**
 * Base class that represents a row from the 'tree_sc' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/28/11 15:03:11
 *
 * @package    lib.model.om
 */
abstract class BaseTreeSc extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TreeScPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the grupo_trabajo_id field.
	 * @var        int
	 */
	protected $grupo_trabajo_id;

	/**
	 * The value for the periodo_id field.
	 * @var        int
	 */
	protected $periodo_id;

	/**
	 * The value for the responsable_id field.
	 * @var        int
	 */
	protected $responsable_id;

	/**
	 * The value for the email_responsable field.
	 * @var        string
	 */
	protected $email_responsable;

	/**
	 * The value for the valor_minimo field.
	 * @var        int
	 */
	protected $valor_minimo;

	/**
	 * The value for the valor_deseado field.
	 * @var        int
	 */
	protected $valor_deseado;

	/**
	 * The value for the configure_flag field.
	 * @var        string
	 */
	protected $configure_flag;

	/**
	 * The value for the flag field.
	 * @var        string
	 */
	protected $flag;

	/**
	 * The value for the create_at field.
	 * @var        string
	 */
	protected $create_at;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * The value for the configure_design field.
	 * @var        string
	 */
	protected $configure_design;

	/**
	 * The value for the produccion field.
	 * @var        string
	 */
	protected $produccion;

	/**
	 * @var        UserSc
	 */
	protected $aUserScRelatedByUserId;

	/**
	 * @var        GrupoTrabajoSc
	 */
	protected $aGrupoTrabajoSc;

	/**
	 * @var        PeriodoSc
	 */
	protected $aPeriodoSc;

	/**
	 * @var        UserSc
	 */
	protected $aUserScRelatedByResponsableId;

	/**
	 * @var        array TreeUser[] Collection to store aggregation of TreeUser objects.
	 */
	protected $collTreeUsers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTreeUsers.
	 */
	private $lastTreeUserCriteria = null;

	/**
	 * @var        array IndicatorsSc[] Collection to store aggregation of IndicatorsSc objects.
	 */
	protected $collIndicatorsScs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collIndicatorsScs.
	 */
	private $lastIndicatorsScCriteria = null;

	/**
	 * @var        array AsignacionSc[] Collection to store aggregation of AsignacionSc objects.
	 */
	protected $collAsignacionScs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAsignacionScs.
	 */
	private $lastAsignacionScCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TreeScPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [grupo_trabajo_id] column value.
	 * 
	 * @return     int
	 */
	public function getGrupoTrabajoId()
	{
		return $this->grupo_trabajo_id;
	}

	/**
	 * Get the [periodo_id] column value.
	 * 
	 * @return     int
	 */
	public function getPeriodoId()
	{
		return $this->periodo_id;
	}

	/**
	 * Get the [responsable_id] column value.
	 * 
	 * @return     int
	 */
	public function getResponsableId()
	{
		return $this->responsable_id;
	}

	/**
	 * Get the [email_responsable] column value.
	 * 
	 * @return     string
	 */
	public function getEmailResponsable()
	{
		return $this->email_responsable;
	}

	/**
	 * Get the [valor_minimo] column value.
	 * 
	 * @return     int
	 */
	public function getValorMinimo()
	{
		return $this->valor_minimo;
	}

	/**
	 * Get the [valor_deseado] column value.
	 * 
	 * @return     int
	 */
	public function getValorDeseado()
	{
		return $this->valor_deseado;
	}

	/**
	 * Get the [configure_flag] column value.
	 * 
	 * @return     string
	 */
	public function getConfigureFlag()
	{
		return $this->configure_flag;
	}

	/**
	 * Get the [flag] column value.
	 * 
	 * @return     string
	 */
	public function getFlag()
	{
		return $this->flag;
	}

	/**
	 * Get the [optionally formatted] temporal [create_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->create_at === null) {
			return null;
		}


		if ($this->create_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->create_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->create_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}


		if ($this->update_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->update_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [configure_design] column value.
	 * 
	 * @return     string
	 */
	public function getConfigureDesign()
	{
		return $this->configure_design;
	}

	/**
	 * Get the [produccion] column value.
	 * 
	 * @return     string
	 */
	public function getProduccion()
	{
		return $this->produccion;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = TreeScPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = TreeScPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = TreeScPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = TreeScPeer::USER_ID;
		}

		if ($this->aUserScRelatedByUserId !== null && $this->aUserScRelatedByUserId->getId() !== $v) {
			$this->aUserScRelatedByUserId = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [grupo_trabajo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setGrupoTrabajoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->grupo_trabajo_id !== $v) {
			$this->grupo_trabajo_id = $v;
			$this->modifiedColumns[] = TreeScPeer::GRUPO_TRABAJO_ID;
		}

		if ($this->aGrupoTrabajoSc !== null && $this->aGrupoTrabajoSc->getId() !== $v) {
			$this->aGrupoTrabajoSc = null;
		}

		return $this;
	} // setGrupoTrabajoId()

	/**
	 * Set the value of [periodo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setPeriodoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->periodo_id !== $v) {
			$this->periodo_id = $v;
			$this->modifiedColumns[] = TreeScPeer::PERIODO_ID;
		}

		if ($this->aPeriodoSc !== null && $this->aPeriodoSc->getId() !== $v) {
			$this->aPeriodoSc = null;
		}

		return $this;
	} // setPeriodoId()

	/**
	 * Set the value of [responsable_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setResponsableId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->responsable_id !== $v) {
			$this->responsable_id = $v;
			$this->modifiedColumns[] = TreeScPeer::RESPONSABLE_ID;
		}

		if ($this->aUserScRelatedByResponsableId !== null && $this->aUserScRelatedByResponsableId->getId() !== $v) {
			$this->aUserScRelatedByResponsableId = null;
		}

		return $this;
	} // setResponsableId()

	/**
	 * Set the value of [email_responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setEmailResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email_responsable !== $v) {
			$this->email_responsable = $v;
			$this->modifiedColumns[] = TreeScPeer::EMAIL_RESPONSABLE;
		}

		return $this;
	} // setEmailResponsable()

	/**
	 * Set the value of [valor_minimo] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setValorMinimo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_minimo !== $v) {
			$this->valor_minimo = $v;
			$this->modifiedColumns[] = TreeScPeer::VALOR_MINIMO;
		}

		return $this;
	} // setValorMinimo()

	/**
	 * Set the value of [valor_deseado] column.
	 * 
	 * @param      int $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setValorDeseado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->valor_deseado !== $v) {
			$this->valor_deseado = $v;
			$this->modifiedColumns[] = TreeScPeer::VALOR_DESEADO;
		}

		return $this;
	} // setValorDeseado()

	/**
	 * Set the value of [configure_flag] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setConfigureFlag($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->configure_flag !== $v) {
			$this->configure_flag = $v;
			$this->modifiedColumns[] = TreeScPeer::CONFIGURE_FLAG;
		}

		return $this;
	} // setConfigureFlag()

	/**
	 * Set the value of [flag] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setFlag($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flag !== $v) {
			$this->flag = $v;
			$this->modifiedColumns[] = TreeScPeer::FLAG;
		}

		return $this;
	} // setFlag()

	/**
	 * Sets the value of [create_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setCreateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->create_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->create_at !== null && $tmpDt = new DateTime($this->create_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->create_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TreeScPeer::CREATE_AT;
			}
		} // if either are not null

		return $this;
	} // setCreateAt()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TreeScPeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Set the value of [configure_design] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setConfigureDesign($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->configure_design !== $v) {
			$this->configure_design = $v;
			$this->modifiedColumns[] = TreeScPeer::CONFIGURE_DESIGN;
		}

		return $this;
	} // setConfigureDesign()

	/**
	 * Set the value of [produccion] column.
	 * 
	 * @param      string $v new value
	 * @return     TreeSc The current object (for fluent API support)
	 */
	public function setProduccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->produccion !== $v) {
			$this->produccion = $v;
			$this->modifiedColumns[] = TreeScPeer::PRODUCCION;
		}

		return $this;
	} // setProduccion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->descripcion = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->user_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->grupo_trabajo_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->periodo_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->responsable_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->email_responsable = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->valor_minimo = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->valor_deseado = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->configure_flag = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->flag = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->create_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->update_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->configure_design = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->produccion = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = TreeScPeer::NUM_COLUMNS - TreeScPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating TreeSc object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUserScRelatedByUserId !== null && $this->user_id !== $this->aUserScRelatedByUserId->getId()) {
			$this->aUserScRelatedByUserId = null;
		}
		if ($this->aGrupoTrabajoSc !== null && $this->grupo_trabajo_id !== $this->aGrupoTrabajoSc->getId()) {
			$this->aGrupoTrabajoSc = null;
		}
		if ($this->aPeriodoSc !== null && $this->periodo_id !== $this->aPeriodoSc->getId()) {
			$this->aPeriodoSc = null;
		}
		if ($this->aUserScRelatedByResponsableId !== null && $this->responsable_id !== $this->aUserScRelatedByResponsableId->getId()) {
			$this->aUserScRelatedByResponsableId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TreeScPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TreeScPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUserScRelatedByUserId = null;
			$this->aGrupoTrabajoSc = null;
			$this->aPeriodoSc = null;
			$this->aUserScRelatedByResponsableId = null;
			$this->collTreeUsers = null;
			$this->lastTreeUserCriteria = null;

			$this->collIndicatorsScs = null;
			$this->lastIndicatorsScCriteria = null;

			$this->collAsignacionScs = null;
			$this->lastAsignacionScCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TreeScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTreeSc:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				TreeScPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTreeSc:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TreeScPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTreeSc:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTreeSc:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TreeScPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUserScRelatedByUserId !== null) {
				if ($this->aUserScRelatedByUserId->isModified() || $this->aUserScRelatedByUserId->isNew()) {
					$affectedRows += $this->aUserScRelatedByUserId->save($con);
				}
				$this->setUserScRelatedByUserId($this->aUserScRelatedByUserId);
			}

			if ($this->aGrupoTrabajoSc !== null) {
				if ($this->aGrupoTrabajoSc->isModified() || $this->aGrupoTrabajoSc->isNew()) {
					$affectedRows += $this->aGrupoTrabajoSc->save($con);
				}
				$this->setGrupoTrabajoSc($this->aGrupoTrabajoSc);
			}

			if ($this->aPeriodoSc !== null) {
				if ($this->aPeriodoSc->isModified() || $this->aPeriodoSc->isNew()) {
					$affectedRows += $this->aPeriodoSc->save($con);
				}
				$this->setPeriodoSc($this->aPeriodoSc);
			}

			if ($this->aUserScRelatedByResponsableId !== null) {
				if ($this->aUserScRelatedByResponsableId->isModified() || $this->aUserScRelatedByResponsableId->isNew()) {
					$affectedRows += $this->aUserScRelatedByResponsableId->save($con);
				}
				$this->setUserScRelatedByResponsableId($this->aUserScRelatedByResponsableId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TreeScPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TreeScPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TreeScPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTreeUsers !== null) {
				foreach ($this->collTreeUsers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collIndicatorsScs !== null) {
				foreach ($this->collIndicatorsScs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAsignacionScs !== null) {
				foreach ($this->collAsignacionScs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUserScRelatedByUserId !== null) {
				if (!$this->aUserScRelatedByUserId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserScRelatedByUserId->getValidationFailures());
				}
			}

			if ($this->aGrupoTrabajoSc !== null) {
				if (!$this->aGrupoTrabajoSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGrupoTrabajoSc->getValidationFailures());
				}
			}

			if ($this->aPeriodoSc !== null) {
				if (!$this->aPeriodoSc->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPeriodoSc->getValidationFailures());
				}
			}

			if ($this->aUserScRelatedByResponsableId !== null) {
				if (!$this->aUserScRelatedByResponsableId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserScRelatedByResponsableId->getValidationFailures());
				}
			}


			if (($retval = TreeScPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTreeUsers !== null) {
					foreach ($this->collTreeUsers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collIndicatorsScs !== null) {
					foreach ($this->collIndicatorsScs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAsignacionScs !== null) {
					foreach ($this->collAsignacionScs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TreeScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getDescripcion();
				break;
			case 3:
				return $this->getUserId();
				break;
			case 4:
				return $this->getGrupoTrabajoId();
				break;
			case 5:
				return $this->getPeriodoId();
				break;
			case 6:
				return $this->getResponsableId();
				break;
			case 7:
				return $this->getEmailResponsable();
				break;
			case 8:
				return $this->getValorMinimo();
				break;
			case 9:
				return $this->getValorDeseado();
				break;
			case 10:
				return $this->getConfigureFlag();
				break;
			case 11:
				return $this->getFlag();
				break;
			case 12:
				return $this->getCreateAt();
				break;
			case 13:
				return $this->getUpdateAt();
				break;
			case 14:
				return $this->getConfigureDesign();
				break;
			case 15:
				return $this->getProduccion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TreeScPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getDescripcion(),
			$keys[3] => $this->getUserId(),
			$keys[4] => $this->getGrupoTrabajoId(),
			$keys[5] => $this->getPeriodoId(),
			$keys[6] => $this->getResponsableId(),
			$keys[7] => $this->getEmailResponsable(),
			$keys[8] => $this->getValorMinimo(),
			$keys[9] => $this->getValorDeseado(),
			$keys[10] => $this->getConfigureFlag(),
			$keys[11] => $this->getFlag(),
			$keys[12] => $this->getCreateAt(),
			$keys[13] => $this->getUpdateAt(),
			$keys[14] => $this->getConfigureDesign(),
			$keys[15] => $this->getProduccion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TreeScPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setDescripcion($value);
				break;
			case 3:
				$this->setUserId($value);
				break;
			case 4:
				$this->setGrupoTrabajoId($value);
				break;
			case 5:
				$this->setPeriodoId($value);
				break;
			case 6:
				$this->setResponsableId($value);
				break;
			case 7:
				$this->setEmailResponsable($value);
				break;
			case 8:
				$this->setValorMinimo($value);
				break;
			case 9:
				$this->setValorDeseado($value);
				break;
			case 10:
				$this->setConfigureFlag($value);
				break;
			case 11:
				$this->setFlag($value);
				break;
			case 12:
				$this->setCreateAt($value);
				break;
			case 13:
				$this->setUpdateAt($value);
				break;
			case 14:
				$this->setConfigureDesign($value);
				break;
			case 15:
				$this->setProduccion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TreeScPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescripcion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUserId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGrupoTrabajoId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPeriodoId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setResponsableId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setEmailResponsable($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setValorMinimo($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setValorDeseado($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setConfigureFlag($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setFlag($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCreateAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUpdateAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setConfigureDesign($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setProduccion($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TreeScPeer::DATABASE_NAME);

		if ($this->isColumnModified(TreeScPeer::ID)) $criteria->add(TreeScPeer::ID, $this->id);
		if ($this->isColumnModified(TreeScPeer::NAME)) $criteria->add(TreeScPeer::NAME, $this->name);
		if ($this->isColumnModified(TreeScPeer::DESCRIPCION)) $criteria->add(TreeScPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(TreeScPeer::USER_ID)) $criteria->add(TreeScPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(TreeScPeer::GRUPO_TRABAJO_ID)) $criteria->add(TreeScPeer::GRUPO_TRABAJO_ID, $this->grupo_trabajo_id);
		if ($this->isColumnModified(TreeScPeer::PERIODO_ID)) $criteria->add(TreeScPeer::PERIODO_ID, $this->periodo_id);
		if ($this->isColumnModified(TreeScPeer::RESPONSABLE_ID)) $criteria->add(TreeScPeer::RESPONSABLE_ID, $this->responsable_id);
		if ($this->isColumnModified(TreeScPeer::EMAIL_RESPONSABLE)) $criteria->add(TreeScPeer::EMAIL_RESPONSABLE, $this->email_responsable);
		if ($this->isColumnModified(TreeScPeer::VALOR_MINIMO)) $criteria->add(TreeScPeer::VALOR_MINIMO, $this->valor_minimo);
		if ($this->isColumnModified(TreeScPeer::VALOR_DESEADO)) $criteria->add(TreeScPeer::VALOR_DESEADO, $this->valor_deseado);
		if ($this->isColumnModified(TreeScPeer::CONFIGURE_FLAG)) $criteria->add(TreeScPeer::CONFIGURE_FLAG, $this->configure_flag);
		if ($this->isColumnModified(TreeScPeer::FLAG)) $criteria->add(TreeScPeer::FLAG, $this->flag);
		if ($this->isColumnModified(TreeScPeer::CREATE_AT)) $criteria->add(TreeScPeer::CREATE_AT, $this->create_at);
		if ($this->isColumnModified(TreeScPeer::UPDATE_AT)) $criteria->add(TreeScPeer::UPDATE_AT, $this->update_at);
		if ($this->isColumnModified(TreeScPeer::CONFIGURE_DESIGN)) $criteria->add(TreeScPeer::CONFIGURE_DESIGN, $this->configure_design);
		if ($this->isColumnModified(TreeScPeer::PRODUCCION)) $criteria->add(TreeScPeer::PRODUCCION, $this->produccion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TreeScPeer::DATABASE_NAME);

		$criteria->add(TreeScPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of TreeSc (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setUserId($this->user_id);

		$copyObj->setGrupoTrabajoId($this->grupo_trabajo_id);

		$copyObj->setPeriodoId($this->periodo_id);

		$copyObj->setResponsableId($this->responsable_id);

		$copyObj->setEmailResponsable($this->email_responsable);

		$copyObj->setValorMinimo($this->valor_minimo);

		$copyObj->setValorDeseado($this->valor_deseado);

		$copyObj->setConfigureFlag($this->configure_flag);

		$copyObj->setFlag($this->flag);

		$copyObj->setCreateAt($this->create_at);

		$copyObj->setUpdateAt($this->update_at);

		$copyObj->setConfigureDesign($this->configure_design);

		$copyObj->setProduccion($this->produccion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTreeUsers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTreeUser($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getIndicatorsScs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addIndicatorsSc($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAsignacionScs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAsignacionSc($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     TreeSc Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TreeScPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TreeScPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a UserSc object.
	 *
	 * @param      UserSc $v
	 * @return     TreeSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserScRelatedByUserId(UserSc $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->aUserScRelatedByUserId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the UserSc object, it will not be re-added.
		if ($v !== null) {
			$v->addTreeScRelatedByUserId($this);
		}

		return $this;
	}


	/**
	 * Get the associated UserSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     UserSc The associated UserSc object.
	 * @throws     PropelException
	 */
	public function getUserScRelatedByUserId(PropelPDO $con = null)
	{
		if ($this->aUserScRelatedByUserId === null && ($this->user_id !== null)) {
			$this->aUserScRelatedByUserId = UserScPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserScRelatedByUserId->addTreeScsRelatedByUserId($this);
			 */
		}
		return $this->aUserScRelatedByUserId;
	}

	/**
	 * Declares an association between this object and a GrupoTrabajoSc object.
	 *
	 * @param      GrupoTrabajoSc $v
	 * @return     TreeSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGrupoTrabajoSc(GrupoTrabajoSc $v = null)
	{
		if ($v === null) {
			$this->setGrupoTrabajoId(NULL);
		} else {
			$this->setGrupoTrabajoId($v->getId());
		}

		$this->aGrupoTrabajoSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the GrupoTrabajoSc object, it will not be re-added.
		if ($v !== null) {
			$v->addTreeSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated GrupoTrabajoSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     GrupoTrabajoSc The associated GrupoTrabajoSc object.
	 * @throws     PropelException
	 */
	public function getGrupoTrabajoSc(PropelPDO $con = null)
	{
		if ($this->aGrupoTrabajoSc === null && ($this->grupo_trabajo_id !== null)) {
			$this->aGrupoTrabajoSc = GrupoTrabajoScPeer::retrieveByPk($this->grupo_trabajo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGrupoTrabajoSc->addTreeScs($this);
			 */
		}
		return $this->aGrupoTrabajoSc;
	}

	/**
	 * Declares an association between this object and a PeriodoSc object.
	 *
	 * @param      PeriodoSc $v
	 * @return     TreeSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPeriodoSc(PeriodoSc $v = null)
	{
		if ($v === null) {
			$this->setPeriodoId(NULL);
		} else {
			$this->setPeriodoId($v->getId());
		}

		$this->aPeriodoSc = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PeriodoSc object, it will not be re-added.
		if ($v !== null) {
			$v->addTreeSc($this);
		}

		return $this;
	}


	/**
	 * Get the associated PeriodoSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PeriodoSc The associated PeriodoSc object.
	 * @throws     PropelException
	 */
	public function getPeriodoSc(PropelPDO $con = null)
	{
		if ($this->aPeriodoSc === null && ($this->periodo_id !== null)) {
			$this->aPeriodoSc = PeriodoScPeer::retrieveByPk($this->periodo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPeriodoSc->addTreeScs($this);
			 */
		}
		return $this->aPeriodoSc;
	}

	/**
	 * Declares an association between this object and a UserSc object.
	 *
	 * @param      UserSc $v
	 * @return     TreeSc The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserScRelatedByResponsableId(UserSc $v = null)
	{
		if ($v === null) {
			$this->setResponsableId(NULL);
		} else {
			$this->setResponsableId($v->getId());
		}

		$this->aUserScRelatedByResponsableId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the UserSc object, it will not be re-added.
		if ($v !== null) {
			$v->addTreeScRelatedByResponsableId($this);
		}

		return $this;
	}


	/**
	 * Get the associated UserSc object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     UserSc The associated UserSc object.
	 * @throws     PropelException
	 */
	public function getUserScRelatedByResponsableId(PropelPDO $con = null)
	{
		if ($this->aUserScRelatedByResponsableId === null && ($this->responsable_id !== null)) {
			$this->aUserScRelatedByResponsableId = UserScPeer::retrieveByPk($this->responsable_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserScRelatedByResponsableId->addTreeScsRelatedByResponsableId($this);
			 */
		}
		return $this->aUserScRelatedByResponsableId;
	}

	/**
	 * Clears out the collTreeUsers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTreeUsers()
	 */
	public function clearTreeUsers()
	{
		$this->collTreeUsers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTreeUsers collection (array).
	 *
	 * By default this just sets the collTreeUsers collection to an empty array (like clearcollTreeUsers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTreeUsers()
	{
		$this->collTreeUsers = array();
	}

	/**
	 * Gets an array of TreeUser objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this TreeSc has previously been saved, it will retrieve
	 * related TreeUsers from storage. If this TreeSc is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TreeUser[]
	 * @throws     PropelException
	 */
	public function getTreeUsers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTreeUsers === null) {
			if ($this->isNew()) {
			   $this->collTreeUsers = array();
			} else {

				$criteria->add(TreeUserPeer::TREE_ID, $this->id);

				TreeUserPeer::addSelectColumns($criteria);
				$this->collTreeUsers = TreeUserPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TreeUserPeer::TREE_ID, $this->id);

				TreeUserPeer::addSelectColumns($criteria);
				if (!isset($this->lastTreeUserCriteria) || !$this->lastTreeUserCriteria->equals($criteria)) {
					$this->collTreeUsers = TreeUserPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTreeUserCriteria = $criteria;
		return $this->collTreeUsers;
	}

	/**
	 * Returns the number of related TreeUser objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TreeUser objects.
	 * @throws     PropelException
	 */
	public function countTreeUsers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTreeUsers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TreeUserPeer::TREE_ID, $this->id);

				$count = TreeUserPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TreeUserPeer::TREE_ID, $this->id);

				if (!isset($this->lastTreeUserCriteria) || !$this->lastTreeUserCriteria->equals($criteria)) {
					$count = TreeUserPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTreeUsers);
				}
			} else {
				$count = count($this->collTreeUsers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TreeUser object to this object
	 * through the TreeUser foreign key attribute.
	 *
	 * @param      TreeUser $l TreeUser
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTreeUser(TreeUser $l)
	{
		if ($this->collTreeUsers === null) {
			$this->initTreeUsers();
		}
		if (!in_array($l, $this->collTreeUsers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTreeUsers, $l);
			$l->setTreeSc($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TreeSc is new, it will return
	 * an empty collection; or if this TreeSc has previously
	 * been saved, it will retrieve related TreeUsers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TreeSc.
	 */
	public function getTreeUsersJoinUserSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTreeUsers === null) {
			if ($this->isNew()) {
				$this->collTreeUsers = array();
			} else {

				$criteria->add(TreeUserPeer::TREE_ID, $this->id);

				$this->collTreeUsers = TreeUserPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TreeUserPeer::TREE_ID, $this->id);

			if (!isset($this->lastTreeUserCriteria) || !$this->lastTreeUserCriteria->equals($criteria)) {
				$this->collTreeUsers = TreeUserPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastTreeUserCriteria = $criteria;

		return $this->collTreeUsers;
	}

	/**
	 * Clears out the collIndicatorsScs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addIndicatorsScs()
	 */
	public function clearIndicatorsScs()
	{
		$this->collIndicatorsScs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collIndicatorsScs collection (array).
	 *
	 * By default this just sets the collIndicatorsScs collection to an empty array (like clearcollIndicatorsScs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initIndicatorsScs()
	{
		$this->collIndicatorsScs = array();
	}

	/**
	 * Gets an array of IndicatorsSc objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this TreeSc has previously been saved, it will retrieve
	 * related IndicatorsScs from storage. If this TreeSc is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array IndicatorsSc[]
	 * @throws     PropelException
	 */
	public function getIndicatorsScs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIndicatorsScs === null) {
			if ($this->isNew()) {
			   $this->collIndicatorsScs = array();
			} else {

				$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

				IndicatorsScPeer::addSelectColumns($criteria);
				$this->collIndicatorsScs = IndicatorsScPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

				IndicatorsScPeer::addSelectColumns($criteria);
				if (!isset($this->lastIndicatorsScCriteria) || !$this->lastIndicatorsScCriteria->equals($criteria)) {
					$this->collIndicatorsScs = IndicatorsScPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastIndicatorsScCriteria = $criteria;
		return $this->collIndicatorsScs;
	}

	/**
	 * Returns the number of related IndicatorsSc objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related IndicatorsSc objects.
	 * @throws     PropelException
	 */
	public function countIndicatorsScs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collIndicatorsScs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

				$count = IndicatorsScPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

				if (!isset($this->lastIndicatorsScCriteria) || !$this->lastIndicatorsScCriteria->equals($criteria)) {
					$count = IndicatorsScPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collIndicatorsScs);
				}
			} else {
				$count = count($this->collIndicatorsScs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a IndicatorsSc object to this object
	 * through the IndicatorsSc foreign key attribute.
	 *
	 * @param      IndicatorsSc $l IndicatorsSc
	 * @return     void
	 * @throws     PropelException
	 */
	public function addIndicatorsSc(IndicatorsSc $l)
	{
		if ($this->collIndicatorsScs === null) {
			$this->initIndicatorsScs();
		}
		if (!in_array($l, $this->collIndicatorsScs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collIndicatorsScs, $l);
			$l->setTreeSc($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TreeSc is new, it will return
	 * an empty collection; or if this TreeSc has previously
	 * been saved, it will retrieve related IndicatorsScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TreeSc.
	 */
	public function getIndicatorsScsJoinUserSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIndicatorsScs === null) {
			if ($this->isNew()) {
				$this->collIndicatorsScs = array();
			} else {

				$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

				$this->collIndicatorsScs = IndicatorsScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(IndicatorsScPeer::TREE_ID, $this->id);

			if (!isset($this->lastIndicatorsScCriteria) || !$this->lastIndicatorsScCriteria->equals($criteria)) {
				$this->collIndicatorsScs = IndicatorsScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastIndicatorsScCriteria = $criteria;

		return $this->collIndicatorsScs;
	}

	/**
	 * Clears out the collAsignacionScs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAsignacionScs()
	 */
	public function clearAsignacionScs()
	{
		$this->collAsignacionScs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAsignacionScs collection (array).
	 *
	 * By default this just sets the collAsignacionScs collection to an empty array (like clearcollAsignacionScs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAsignacionScs()
	{
		$this->collAsignacionScs = array();
	}

	/**
	 * Gets an array of AsignacionSc objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this TreeSc has previously been saved, it will retrieve
	 * related AsignacionScs from storage. If this TreeSc is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AsignacionSc[]
	 * @throws     PropelException
	 */
	public function getAsignacionScs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
			   $this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				AsignacionScPeer::addSelectColumns($criteria);
				$this->collAsignacionScs = AsignacionScPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				AsignacionScPeer::addSelectColumns($criteria);
				if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
					$this->collAsignacionScs = AsignacionScPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAsignacionScCriteria = $criteria;
		return $this->collAsignacionScs;
	}

	/**
	 * Returns the number of related AsignacionSc objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AsignacionSc objects.
	 * @throws     PropelException
	 */
	public function countAsignacionScs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				$count = AsignacionScPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
					$count = AsignacionScPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAsignacionScs);
				}
			} else {
				$count = count($this->collAsignacionScs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AsignacionSc object to this object
	 * through the AsignacionSc foreign key attribute.
	 *
	 * @param      AsignacionSc $l AsignacionSc
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAsignacionSc(AsignacionSc $l)
	{
		if ($this->collAsignacionScs === null) {
			$this->initAsignacionScs();
		}
		if (!in_array($l, $this->collAsignacionScs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAsignacionScs, $l);
			$l->setTreeSc($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TreeSc is new, it will return
	 * an empty collection; or if this TreeSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TreeSc.
	 */
	public function getAsignacionScsJoinGrupoTrabajoSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinGrupoTrabajoSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinGrupoTrabajoSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TreeSc is new, it will return
	 * an empty collection; or if this TreeSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TreeSc.
	 */
	public function getAsignacionScsJoinIndicatorsSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinIndicatorsSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinIndicatorsSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TreeSc is new, it will return
	 * an empty collection; or if this TreeSc has previously
	 * been saved, it will retrieve related AsignacionScs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TreeSc.
	 */
	public function getAsignacionScsJoinUserSc($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TreeScPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsignacionScs === null) {
			if ($this->isNew()) {
				$this->collAsignacionScs = array();
			} else {

				$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsignacionScPeer::TREE_ID, $this->id);

			if (!isset($this->lastAsignacionScCriteria) || !$this->lastAsignacionScCriteria->equals($criteria)) {
				$this->collAsignacionScs = AsignacionScPeer::doSelectJoinUserSc($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsignacionScCriteria = $criteria;

		return $this->collAsignacionScs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTreeUsers) {
				foreach ((array) $this->collTreeUsers as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collIndicatorsScs) {
				foreach ((array) $this->collIndicatorsScs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAsignacionScs) {
				foreach ((array) $this->collAsignacionScs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTreeUsers = null;
		$this->collIndicatorsScs = null;
		$this->collAsignacionScs = null;
			$this->aUserScRelatedByUserId = null;
			$this->aGrupoTrabajoSc = null;
			$this->aPeriodoSc = null;
			$this->aUserScRelatedByResponsableId = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTreeSc:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTreeSc::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTreeSc
